# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('anonymity', ['internet','point-to-point','point-to-point-layout'])
    module.source = [
        'model/arap-node.cc',
        'model/arap-ants.cc',
        'model/arap-simulator.cc',
				'model/arap-path-manager.cc',
        'model/explorer-ants-statistics.cc',
        'model/routing-table-row.cc',
        'model/smart-path-manager.cc',
        'model/path-manager-factory.cc',
        'model/load-ants-statistics.cc',
        'helper/anonymity-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('anonymity')
    module_test.source = [
        'test/anonymity-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'anonymity'
    headers.source = [
    		'model/arap-definitions.h',
				'model/arap-node.h',
        'model/arap-ants.h',
        'model/arap-simulator.h',
        'model/arap-path-manager.h',
        'model/explorer-ants-statistics.h',
        'model/routing-table-row.h',
        'model/smart-path-manager.h',
        'model/path-manager-factory.h',
        'model/load-ants-statistics.h',
        'helper/anonymity-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

